name: gym
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  cloud_firestore: ^5.0.1
  cupertino_icons: ^1.0.6
  dropdown_button2: ^2.3.9
  email_validator: ^2.1.17
  equatable: ^2.0.5
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  firebase_storage: ^12.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_rating_bar: ^4.0.1
  flutter_styled_toast: ^2.2.1
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.6
  google_sign_in: ^6.2.1
  image: ^4.2.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  lottie: ^3.1.2
  shimmer: ^3.0.0
  syncfusion_flutter_datepicker: ^29.2.10
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/img/
    - assets/lottie/
