// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWFU4TM9PqbYh24j2tiVO8l9KlBhXn_9I',
    appId: '1:50076187923:web:d9a385acb65f0126f06ee6',
    messagingSenderId: '50076187923',
    projectId: 'wahab-14612',
    authDomain: 'wahab-14612.firebaseapp.com',
    storageBucket: 'wahab-14612.firebasestorage.app',
    measurementId: 'G-LG2ZQLMHTC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANBl3DnP95sowg6CochPH1dhVpi9lI958',
    appId: '1:50076187923:android:c453227aa8e50e1af06ee6',
    messagingSenderId: '50076187923',
    projectId: 'wahab-14612',
    storageBucket: 'wahab-14612.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxnBEzccQwyhUb7yBclJU1mJ8_0M3J3oU',
    appId: '1:50076187923:ios:a69a954bedbe5243f06ee6',
    messagingSenderId: '50076187923',
    projectId: 'wahab-14612',
    storageBucket: 'wahab-14612.firebasestorage.app',
    iosBundleId: 'com.example.gym',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxnBEzccQwyhUb7yBclJU1mJ8_0M3J3oU',
    appId: '1:50076187923:ios:8f9ac67fd95de9b4f06ee6',
    messagingSenderId: '50076187923',
    projectId: 'wahab-14612',
    storageBucket: 'wahab-14612.firebasestorage.app',
    iosBundleId: 'com.example.awais',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWFU4TM9PqbYh24j2tiVO8l9KlBhXn_9I',
    appId: '1:50076187923:web:262ee80695f4f15df06ee6',
    messagingSenderId: '50076187923',
    projectId: 'wahab-14612',
    authDomain: 'wahab-14612.firebaseapp.com',
    storageBucket: 'wahab-14612.firebasestorage.app',
    measurementId: 'G-F1KLDV6MCY',
  );

}